apiVersion: apps/v1
kind: Deployment
metadata:
  name: poridhi-svc2
  namespace: devops
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: poridhi-svc2
  template:
    metadata:
      labels:
        app: poridhi-svc2
    spec:
      containers:
      - name: poridhi-svc2
        image: shajalahamedcse/poridhi-svc2:v1.0.5  # Replace with your actual Docker image
        ports:
        - containerPort: 3000  # Adjust the port if your Node.js app is running on a different port
---
apiVersion: v1
kind: Service
metadata:
  name: poridhi-sv2-svc
  namespace: devops
spec:
  selector:
    app: poridhi-svc2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Adjust if your Node.js app is running on a different port
      nodePort: 30001  # Specify the desired nodePort value here
  type: ClusterIP  # Change to NodePort or ClusterIP based on your requirements
